0: #num
  - 0 #channel
  - 9 #speed
  - 200 #min value
  - 500 #max value
1:
  - 1 #channel
  - 100 #speed
  - 350 #min value
  - 115 #max value
2:
  - 2 #channel
  - 100 #speed
  - 320 #min value
  - 100 #max value
3:
  - 3 #channel
  - 50 #speed
  - 200 #min value
  - 400 #max value

