0: #num
  - 0 #channel
  - 20 #speed
  - 200 #min value
  - 500 #max value
1:
  - 1 #channel
  - 20 #speed
  - 500 #min value
  - 200 #max value
2:
  - 2 #channel
  - 20 #speed
  - 500 #min value
  - 200 #max value