############################################ МАРШРУТ 1
tasks:
  obezd_govna:
    - call: AdjustOn
    - change_cost: 10
    - score: 4                  # ставим статуэтку и витрину
    #- move: 1.7/0.61/0
    #- sleep: 0.5
    - move: 1.7/2.43/-1.047  # фишки больше не мешают 

  get_flipped: 
    - move: 1.68/2.04/-1.047
    - change_cost: 70
    - move: 1.68/1.7/-1.047
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.7/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.7/-1.047
    - score: 1
    - change_cost: 10
    - move: 1.68/2.01/-1.047
    - move: 1.8/2.01/-1.047
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - score: 3
    - call: ValveOff
    - move: 1.68/2.01/-1.047
    - call: ArmDown
    - sleep: 0.3
   

  get_flipped2:
    - move: 1.78/1.7/-1.047  
    - move: 1.68/1.7/-1.047             #ebashim do 2 fihki
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.7/-1.047                #  вроде норм подьезд
    - sleep: 0.2             
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.7/-1.047
    - score: 1
    - move: 1.68/2.25/-1.047
    - move: 1.8/2.25/-1.047
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - score: 3
    - call: ValveOff
    - move: 1.68/2.25/-1.047
    - call: ArmDown

  get_flipped3:
    - move: 1.68/1.7/-1.047
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.7/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.7/-1.047
    - score: 1
    - move: 1.68/2.43/-1.047
    - move: 1.8/2.43/-1.047
    #- call: ArmHalfUp
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - call: ValveOff
    - score: 3
    - move: 1.68/2.43/-1.047
    - call: ArmDown

  bokovaia1:
    - move: 0.76/2.6/0.586
    - move: 0.76/2.6/0.586
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 0.76/2.77/0.586
    - sleep: 0.3
    - call: ArmMegaUp
    - sleep: 0.3
    - score: 1
    - move: 0.76/2.6/0.586
    - move: 0.7/2.51/1.365
    - sleep: 0.3
    - move: 0.5/2.51/1.365
    - sleep: 0.2
    - move: 0.315/2.725/1.365
    - move: 0.315/2.725/1.365
    - call: PumpOff
    - sleep: 0.2
    - call: ValveOn
    - score: 5
    - call: ValveOff

  parkovka:
    - change_cost: 70
    - move: 0.74/2.26/1.375
    - score: 20 
    - route_stop: epics
interrupts:              
  end_inter:
    - interrupt_condition: timers/main/99
    - call: PumpOff
