############################################ МАРШРУТ 1
tasks:

  obezd_govna:
    - change_cost: 7
    - score: 4                  # ставим статуэтку и витрину
    #- move: 1.7/0.61/0
    #- sleep: 0.5
    - move: 1.7/0.61/-1.047  # фишки больше не мешают 

  get_flipped: 
    - move: 1.68/1.34/-1.047
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.34/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.39/-1.047
    - score: 1
  
  deliver_blue_flipped:
    - log: "W: Delivering blue"
    - move: 1.68/0.61/-1.047
    - move: 1.8/0.61/-1.047
    #- call: ArmHalfUp
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - call: ValveOff
    - score: 3
  get_flipped2:
    - move: 1.68/0.61/-1.047
    - call: ArmDown
    - move: 1.68/1.34/-1.047             #ebashim do 2 fihki
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.34/-1.047                #  вроде норм подьезд
    - sleep: 0.2             
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.34/-1.047
    - score: 1
    
  green_flipped2:
    - move: 1.68/0.79/-1.047
    - move: 1.8/0.79/-1.047
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - score: 3
    - call: ValveOff
    - move: 1.68/0.79/-1.047
    - call: ArmDown

  get_flipped3:
    - move: 1.68/1.34/-1.047
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.34/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.34/-1.047
    - score: 1

  red_flipped:
    - move: 1.68/1.03/-1.047
    - move: 1.8/1.03/-1.047
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - score: 3
    - call: ValveOff
    - move: 1.68/1.03/-1.047
    - call: ArmDown
    - move: 1.25/1.03/-1.047

  tolkaem_fishku:
    - log: "W: Going home!"
    - move: 1.4/0.25/-2.56
    - score: 1
    - move: 1.4/0.53/-2.56
    - sleep: 0.2
    - move: 1.4/0.53/-2.56

  bokovaia1:
    - move: 0.76/0.44/-2.56
    - move: 0.76/0.44/-2.56
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 0.76/0.27/-2.56
    - sleep: 0.3
    - call: ArmMegaUp
    - sleep: 0.3
    - score: 1
    - move: 0.76/0.44/-2.56
   # - call: PumpOff
   
  get_flippedbok:
    - move: 0.5/0.53/-3.44
    - sleep: 0.2
    - move: 0.3/0.3/-3.43
    - call: ValveOn
    - call: PumpOff
    - score: 5
    - call: ValveOff

  parkovka:
    - change_cost: 70
    - move: 0.74/0.78/-3.43
    - score: 20 
    - route_stop: epic
    

variables: #MUST BE INTS
  default: 0
  get_flipped_var: 1 
# interrupts:              # едем домой (врубить после теста всего маршрута)
#   return_to_base:
#     - interrupt_condition: "timers/main/50"
#     - move: 1/1/0
