############################################ МАРШРУТ 1
tasks:



  boba_prediction:
    - score: 35


  obezd_govna:
    - call: AdjustOn
    - change_cost: 50
    - score: 4                  # ставим статуэтку и витрину
    - move: 1.7/0.61/-1.047  # фишки больше не мешают 
    - change_cost: 8
    - call: AdjustOn

  get_flipped: 
    #- move: 1.68/1/-1.047
    - move: 1.68/1.34/-1.047
    - call: ArmHalfDown
    - sleep: 0.2
    - call: PumpOn
    - move: 1.78/1.34/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.39/-1.047
    - score: 1
    - move: 1.68/1.03/-1.047
    - move: 1.8/1.03/-1.047
    - sleep: 0.2
    - call: PumpOff
    - sleep: 0.2
    - call: ValveOn
    #- sleep: 0.3
    
    - score: 3
    - call: ValveOff
    - move: 1.64/1.03/-1.047
    - call: ArmDown
    - sleep : 0.2
   

  get_flipped2:
    - move: 1.78/1.34/-1.047  
    - move: 1.68/1.34/-1.047             #ebashim do 2 fihki
    - call: ArmHalfDown
    - sleep: 0.2
    - call: PumpOn
    - move: 1.78/1.34/-1.047                #  вроде норм подьезд
    - sleep: 0.2             
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.34/-1.047
    - score: 1
    - move: 1.68/0.79/-1.047
    - move: 1.8/0.79/-1.047
    - sleep: 0.2
    - call: PumpOff
    - sleep: 0.2
    - call: ValveOn
    - sleep: 0.3
    
    - score: 3
    - call: ValveOff
    - move: 1.64/0.79/-1.047
    - call: ArmDown

  get_flipped3:
    - move: 1.68/1.34/-1.047
    - call: ArmHalfDown
    - sleep: 0.2
    - call: PumpOn
    - move: 1.78/1.34/-1.047
    - sleep: 0.1
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.34/-1.047
    - score: 1
    - move: 1.68/0.61/-1.047
    - move: 1.8/0.61/-1.047
    #- call: ArmHalfUp
    - sleep: 0.4
    - call: PumpOff
    - sleep: 0.3
    - call: ValveOn
    - sleep: 0.2
    - call: ValveOff
    - score: 3
    - move: 1.64/0.61/-1.047
    - call: ArmDown
  bokovaia1:
    - move: 0.77/0.44/-2.56
    - move: 0.77/0.44/-2.56
    - call: ArmBokovaya
    - sleep: 0.2
    - call: PumpOn
    - move: 0.77/0.27/-2.56
    - sleep: 0.3
    - call: ArmHalfUp
    - sleep: 0.3
    - score: 1
    - move: 0.77/0.44/-2.56
    - move: 0.7/0.53/-3
    - sleep: 0.3
    - move: 0.5/0.53/-3.44
    - call: ArmUp
    - call: ArmMegaUp
    - sleep: 0.2
    - move: 0.315/0.315/-3.4
    - move: 0.315/0.315/-3.4
    - call: ArmUp
    - call: PumpOff
    - sleep: 0.1
    - call: ValveOn
    - sleep: 0.2
    - score: 5
    - call: ValveOff

  parkovka:
    - change_cost: 30
    - move: 0.74/0.78/-3.43 
    - score: 20 
    - call: PumpOff
    - route_stop: epics
interrupts:              
  park_inter:
    - interrupt_condition: timers/main/93
    - change_cost: 30
    - move: 0.74/0.78/-3.43
    - call: PumpOff   
    - score: 20  
  #   - condition:
  #     - if: parkovka/move/0/done
  #     - do: 
  #       - log: E:Already in base!
  #     - else:
  #       - score: 20  
  end_inter:
    - interrupt_condition: timers/main/99
    - change_cost: 0
    - call: PumpOff
    - route_stop: epics
