tasks: #move: x/y/th
  init:
    - call: AdjustOn
    - call: PumpOn
    - sleep: 0.5
    - call: PumpOff
    - call: ArmUp
    - sleep: 1
    - call: ArmDown
    - sleep: 1
    - call: ValveOn
    - sleep: 0.5
    - call: ValveOff
    - change_cost: 60
  top_right: 
    - move: 1.62/0.22/-1.74
    - move: 1.62/0.44/0
    - move: 1.62/0.22/-1.74
  start:
    - move: 1.44/0.22/-1.74
    - score: 1000
    #- change_cost: 7


