############################################ МАРШРУТ 1
tasks:
  obezd_govna:
    - change_cost: 7
    - score: 4                  # ставим статуэтку и витрину
    #- move: 1.7/2.43/0
    #- sleep: 0.5
    - move: 1.7/2.43/-1.047  # фишки больше не мешают 

  get_flipped: 
    - move: 1.68/1.69/-1.047
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.69/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.69/-1.047
    - score: 1
    - move: 1.68/2.43/-1.047 
    
  deliver_blue_flipped:
    - move: 1.68/2.01/-1.047
    - move: 1.8/2.01/-1.047
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - score: 3
    - call: ValveOff
    - move: 1.68/2.01/-1.047
    - call: ArmDown
    

  get_flipped2:       
    
    - move: 1.68/1.69/-1.047             #ebashim do 2 fihki
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.69/-1.047                #  вроде норм подьезд
    - sleep: 0.2             
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.69/-1.047
    - score: 1
    
  green_flipped2:
    - change_cost: 70
    - move: 1.68/2.55/-1.047
    - move: 1.68/2.25/-1.047
    - change_cost: 10
    - move: 1.8/2.25/-1.047
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - score: 3
    - call: ValveOff
    - move: 1.68/2.25/-1.047
    - call: ArmDown

  get_flipped3:
    - move: 1.68/1.69/-1.047
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.69/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.69/-1.047
    - score: 1

  red_flipped:
    - log: "W: Delivering blue"
    - move: 1.68/2.43/-1.047
    - move: 1.8/2.43/-1.047
    #- call: ArmHalfUp
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - call: ValveOff
    - score: 3

  tolkaem_fishku:
    - log: "W: Going home!"
    - move: 1.4/2.79/0
    - move: 1.4/2.51/0
    - sleep: 0.2
    - move: 1.4/2.51/0.3

  bokovaia1:
    - move: 0.76/2.6/0.3
    - move: 0.76/2.6/0.3
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 0.76/2.77/0.3
    - sleep: 0.3
    - call: ArmMegaUp
    - sleep: 0.3
    - score: 1
    - move: 0.76/2.6/0.3
   # - call: PumpOff
   
  get_flippedbok:
    - move: 0.5/2.51/1.5
    - sleep: 0.2
    - move: 0.3/2.74/1.5
    - call: ValveOn
    - call: PumpOff
    - score: 5
    - call: ValveOff

  parkovka:
    - change_cost: 70
    - move: 0.74/2.20/1.5
    - score: 20 
    - route_stop: epic
    

variables: #MUST BE INTS
  default: 0
  get_flipped_var: 1 
interrupts: 
  end_inter:
    - interrupt_condition: timers/main/99
    - call: PumpOff
