############################################ МАРШРУТ 1
tasks:
  boba_prediction:
    - score: 35
  obezd_govna:
    - call: AdjustOn
    - score: 4                  # ставим статуэтку и витрину
    - change_cost: 50
    - move: 1.7/2.43/-1.047  # фишки больше не мешают 
    - change_cost: 8
    - call: AdjustOn
  get_flipped: 
    #- move: 1.68/2.04/-1.047
    - move: 1.68/1.73/-1.047
    - call: ArmHalfDown
    - sleep: 0.2
    - call: PumpOn
    - move: 1.78/1.7/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.7/-1.047
    - score: 1
    - move: 1.68/2.01/-1.047
    - move: 1.8/2.01/-1.047
    - sleep: 0.3
    - call: PumpOff
    - sleep: 0.1
    - call: ValveOn
    - sleep: 0.3
    - score: 3
    - call: ValveOff
    - move: 1.64/2.01/-1.047
    - call: ArmDown
    - sleep: 0.3
  get_flipped2:
    - move: 1.78/1.7/-1.047  
    - move: 1.68/1.7/-1.047             #ebashim do 2 fihki
    - call: ArmHalfDown
    - sleep: 0.2
    - call: PumpOn
    - move: 1.78/1.7/-1.047                #  вроде норм подьезд
    - sleep: 0.2             
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.7/-1.047
    - score: 1
    - move: 1.68/2.25/-1.047
    - move: 1.8/2.25/-1.047
    - sleep: 0.3
    - call: PumpOff
    - sleep: 0.1
    - call: ValveOn
    - score: 3
    - call: ValveOff
    - move: 1.64/2.25/-1.047
    - call: ArmDown
  get_flipped3:
    - move: 1.68/1.7/-1.047
    - call: ArmHalfDown
    - sleep: 0.2
    - call: PumpOn
    - move: 1.78/1.7/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.7/-1.047
    - score: 1
    - move: 1.68/2.43/-1.047
    - move: 1.8/2.43/-1.047
    - sleep: 0.3
    - call: PumpOff
    - sleep: 0.3
    - call: ValveOn
    - call: ValveOff
    - score: 3
    - move: 1.64/2.43/-1.047
    - call: ArmDown
  bokovaia1:
    - move: 1.3/2.6/0.586
    - sleep: 0.3
    - move: 0.77/2.6/0.586
    - move: 0.77/2.6/0.586
    - call: ArmBokovaya
    - sleep: 0.2
    - call: PumpOn
    - move: 0.77/2.77/0.586
    - call: ArmHalfUp
    - sleep: 0.1
    - score: 1
    - move: 0.77/2.6/0.586
    - move: 0.7/2.51/1.365
    - sleep: 0.3
    - move: 0.5/2.51/1.365
    - call: ArmUp
    - call: ArmMegaUp
    - sleep: 0.2
    - move: 0.315/2.725/1.365
    - move: 0.315/2.725/1.365
    - call: ArmUp
    - call: PumpOff
    - sleep: 0.1
    - call: ValveOn
    - score: 5
    - sleep: 0.1
    - call: ValveOff
  parkovka:
    - change_cost: 30
    - move: 0.74/2.26/1.375
    - call: PumpOff
    - score: 20 
    - route_stop: epics
interrupts:    
  park_inter:
    - interrupt_condition: timers/main/93
    - change_cost: 30
    - move: 0.74/2.26/1.375   
    - score: 20     
  end_inter:
    - interrupt_condition: timers/main/99
    - change_cost: 0
    - call: PumpOff
    - route_stop: epics
