############################################ МАРШРУТ 1
tasks:

  obezd_govna:
    - call: AdjustOff
    - change_cost: 70
    - score: 4                  # ставим статуэтку и витрину
    #- move: 1.7/0.61/0
    #- sleep: 0.5
    - move: 1.7/0.61/-1.047  # фишки больше не мешают 
    - call: AdjustOn

  get_flipped: 
    - move: 1.68/1/-1.047
    #- change_cost: 70
    - move: 1.68/1.34/-1.047
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.34/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.39/-1.047
    - score: 1
    - change_cost: 10
    - move: 1.68/1.03/-1.047
    - move: 1.8/1.03/-1.047
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - score: 3
    - call: ValveOff
    - move: 1.68/1.03/-1.047
    - call: ArmDown
    - sleep : 0.2
   

  get_flipped2:
    - move: 1.78/1.34/-1.047  
    - move: 1.68/1.34/-1.047             #ebashim do 2 fihki
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.34/-1.047                #  вроде норм подьезд
    - sleep: 0.2             
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.34/-1.047
    - score: 1
    - move: 1.68/0.79/-1.047
    - move: 1.8/0.79/-1.047
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - score: 3
    - call: ValveOff
    - move: 1.68/0.79/-1.047
    - call: ArmDown

  get_flipped3:
    - move: 1.68/1.34/-1.047
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 1.78/1.34/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.34/-1.047
    - score: 1
    - move: 1.68/0.61/-1.047
    - move: 1.8/0.61/-1.047
    #- call: ArmHalfUp
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - call: ValveOff
    - score: 3
    - move: 1.68/0.61/-1.047
    - call: ArmDown
  bokovaia1:
    - move: 0.77/0.44/-2.56
    - move: 0.77/0.44/-2.56
    - call: ArmHalfDown
    - sleep: 0.4
    - call: PumpOn
    - move: 0.77/0.27/-2.56
    - sleep: 0.3
    - call: ArmMegaUp
    - sleep: 0.3
    - score: 1
    - move: 0.77/0.44/-2.56
    - move: 0.7/0.53/-3
    - sleep: 0.3
    - move: 0.5/0.53/-3.44
    - sleep: 0.2
    - move: 0.315/0.315/-3.4
    - move: 0.315/0.315/-3.4
    - call: PumpOff
    - sleep: 0.2
    - call: ValveOn
    - score: 5
    - call: ValveOff

  parkovka:
    - change_cost: 70
    - move: 0.74/0.78/-3.43
    - score: 20 
    - route_stop: epics
interrupts:              
  park_inter:
    - interrupt_condition: timers/main/96
    - change_cost: 70
    - move: 0.74/0.78/-3.43    
  end_inter:
    - interrupt_condition: timers/main/99
    - change_cost: 0
    - call: PumpOff
    - route_stop: epics
