############################################ МАРШРУТ 1
tasks:

   za_statuetkoi:
    - move : 0.51/0.56/xx
    - call : MicroArmHalf
    - call: PumOn
    - sleep: 0.2
    - move: 0.43/0.45/xx
    - call: MicroArmUp

   zamena:
    - move: 0.43/0.45/xx    ##поворачиваемся к реплике
    - move : 0.4/0.36/xx
    - call : KubOtput
    - sleep: 0.1
    - call: KubInput

   sgruz:
    - move: 1.83/0.23/xx   
    - move: 1.7/0.23/xx
    - call: MicroArmDown

  izmerenie1:
   - move: 0.16/0.77/xx
   

  

    

variables: #MUST BE INTS
  default: 0
  get_flipped_var: 1 
#interrupts: 
  # return_to_base:
  #   - interrupt_condition: "timers/main/40"
  #   - move: 1/0.4/1.5 
