tasks:
  izmer0:
    - call: Izmerenie
    - sleep: 1 
    - call: Ohms
    
  izmer1:
    - call: Izmerenie
    - sleep: 1 
    - call: Ohms
    
  izmer2:
    - call: Izmerenie
    - sleep: 1 
    - call: Ohms
    
  izmer3:
    - call: Izmerenie
    - sleep: 1 
    - call: Ohms
    
  izmer4:
    - call: Izmerenie
    - sleep: 1 
    - call: Ohms
    
  izmer5:
    - call: Izmerenie
    - sleep: 1 
    - call: Ohms
    
  loop:
    - goto: izmer0
interrupts:
  flip!:
    - interrupt_condition: izmer0/call/1/purple
    - interrupt_condition: izmer1/call/1/purple
    - interrupt_condition: izmer2/call/1/purple
    - interrupt_condition: izmer3/call/1/purple
    - interrupt_condition: izmer4/call/1/purple
    - interrupt_condition: izmer5/call/1/purple
    - call: NadoPlitka
    - sleep: 1
    - call: NeNadoPlitka
  no_flip!:  
    - interrupt_condition: izmer0/call/1/yellow
    - interrupt_condition: izmer1/call/1/yellow
    - interrupt_condition: izmer2/call/1/yellow
    - interrupt_condition: izmer3/call/1/yellow
    - interrupt_condition: izmer4/call/1/yellow
    - interrupt_condition: izmer5/call/1/yellow
    - interrupt_condition: izmer0/call/1/red
    - interrupt_condition: izmer1/call/1/red
    - interrupt_condition: izmer2/call/1/red
    - interrupt_condition: izmer3/call/1/red
    - interrupt_condition: izmer4/call/1/red
    - interrupt_condition: izmer5/call/1/red
    - call: NeNadoPlitka