############################################ МАРШРУТ 1
tasks:

  za_statuetkoi:
    - call: AdjustOn
    - call: NeNadoPlitka
    - change_cost: 50
    - move : 1/2.6/0.23
    - change_cost: 8
    - call: AdjustOn
    - move : 0.49/2.58/0.2
    - sleep: 0.5
    - move : 0.49/2.58/0.2
    - call : MicroArmHalf
    - call: PumpOn
    - sleep: 0.2
    - move: 0.37/2.7/0.2
    - call: MicroArmUp

  zamena:
    - move: 0.43/2.6/-3.78    ##поворачиваемся к реплике
    - move : 0.4/2.69/-3.78
    - sleep: 0.2
    - call : KubOutput
    - sleep: 0.4
    - call: KubInput
    - sleep: 0.2

  sgruz:
    - move: 1.6/2.84/-2.10  
    - move: 1.79/2.84/-2.10   
    - call : MicroArmHalf
    - sleep: 0.5
    - call: PumpOff
    - sleep: 0.2
    - call: ValveOn
    - sleep: 0.1
    - call: ValveOff
    - move: 1.7/2.81/-2.10
    - change_cost: 7
    - move: 1.6/2.81/-2.10
    - call: MicroArmDown

  damn:
    - move: 0.8/2.55/0
    - sleep: 0.5
    - move: 0.4/2.39/0
    - sleep: 0.5
    - move: 0.4/2.39/2.09
    - call: PumpOff

  # izmerenie0:
  #   - move: 0.3/2.405/2.09
  #   - move: 0.193/2.405/2.09
  #   - call: Izmerenie
  #   - call: Ohms
  #   - sleep: 0.8

  izmerenie1:
    - move : 0.18/2.23/2.09
    - call: Izmerenie
    - call: Ohms
    - sleep: 0.2
    - call: NadoPlitka
    - sleep: 0.1
    - call: NeNadoPlitka
    

  # izmerenie2:
  #  - move: 0.193/2.012/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 0.8

  # izmerenie3:
  #  - move: 0.193/1.815/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 0.8

  # izmerenie4:
  #  - move: 0.193/1.62/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 0.8

  # izmerenie5:
  #  - move: 0.193/1.42/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 0.8

  # izmerenie6:
  #  - move: 0.193/1.22/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 0.8

  parkovka:
   - move: 0.45/1.82/2.09
   - call: PumpOff
   - score: 20
   - route_stop: epic

interrupts:
  flip!:
    - interrupt_condition: izmerenie0/call/1/purple
    - interrupt_condition: izmerenie1/call/1/purple
    - interrupt_condition: izmerenie2/call/1/purple
    - interrupt_condition: izmerenie3/call/1/purple
    - interrupt_condition: izmerenie4/call/1/purple
    - interrupt_condition: izmerenie5/call/1/purple
    - interrupt_condition: izmerenie6/call/1/purple
    - call: NadoPlitka
    - sleep: 0.4
    - call: NeNadoPlitka
  no_flip!:  
    - interrupt_condition: izmerenie0/call/1/yellow
    - interrupt_condition: izmerenie1/call/1/yellow
    - interrupt_condition: izmerenie2/call/1/yellow
    - interrupt_condition: izmerenie3/call/1/yellow
    - interrupt_condition: izmerenie4/call/1/yellow
    - interrupt_condition: izmerenie5/call/1/yellow
    - interrupt_condition: izmerenie6/call/1/yellow
    - interrupt_condition: izmerenie0/call/1/red
    - interrupt_condition: izmerenie1/call/1/red
    - interrupt_condition: izmerenie2/call/1/red
    - interrupt_condition: izmerenie3/call/1/red
    - interrupt_condition: izmerenie4/call/1/red
    - interrupt_condition: izmerenie5/call/1/red
    - interrupt_condition: izmerenie6/call/1/red
    - call: NeNadoPlitka
  park_inter:
    - interrupt_condition: timers/main/96
    - change_cost: 70
    - move: 0.45/1.82/2.09
    - score: 20  
    # - condition:
    #   - if: parkovka/move/0/done
    #   - do: 
    #     - log: E:Already in base!
    #   - else:
    #     - score: 20  
  end_inter:
    - interrupt_condition: timers/main/99
    - change_cost: 0
    - call: PumpOff
    - route_stop: epic
