tasks: #move: x/y/th
  init:
    - call: AdjustOn
    - call: PumpOn
    - sleep: 0.5
    - call: PumpOff
    - call: MicroArmHalf
    - sleep: 1
    - call: MicroArmDown
    - sleep: 0.5
    - call: ValveOn
    - sleep: 0.5
    - call: ValveOff
    - change_cost: 60
  top_left:
    - move: 1.02/2.68/-1.57
  start:
    - move: 1.2/2.85/-1.57
    - score: 1000