############################################ МАРШРУТ 1
tasks:

  za_statuetkoi:
    - call: NeNadoPlitka
    - call: AdjustOn
    - change_cost: 50
    - move : 1/0.44/1.8
    - change_cost: 8
    - call: AdjustOn
    - move : 0.49/0.42/1.812
    - sleep: 0.5
    - move : 0.49/0.42/1.812
    - call : MicroArmHalf
    - call: PumpOn
    - sleep: 0.2
    - move: 0.37/0.34/1.8
    - call: MicroArmUp

  zamena:
    - move: 0.43/0.44/-2.134    ##поворачиваемся к реплике
    - move : 0.4/0.35/-2.134
    - sleep: 0.2
    - call : KubOutput
    - sleep: 0.4
    - call: KubInput
    - sleep: 0.2

  sgruz:
    - move: 1.6/0.2/-2.10  
    - move: 1.805/0.2/-2.10   
    - call : MicroArmHalf
    - sleep: 0.5
    - call: PumpOff
    - sleep: 0.2
    - call: ValveOn
    - sleep: 0.1
    - call: ValveOff
    - move: 1.7/0.23/-2.10
    - move: 1.6/0.23/-2.10
    - call: MicroArmDown
    
  damn:
    - move: 0.4/0.84/0
    - call: PumpOff
  # izmerenie0:
  #   - move: 0.4/0.68/2.09
  #   - call: PumpOff
  #   - move: 0.193/0.68/2.09
  #   - call: Izmerenie
  #   - call: Ohms
  #   - sleep: 0.2

  izmerenie1:
    - move : 0.193/0.84/2.09
    # - call: Izmerenie
    # - call: Ohms
    - sleep: 0.2
    - call: NadoPlitka
    - sleep: 0.4
    - call: NeNadoPlitka
    - sleep: 0.5
    

  # izmerenie2:
  #  - move: 0.193/1.04/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 1

  # izmerenie3:
  #  - move: 0.193/1.22/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 1

  # izmerenie4:
  #  - move: 0.193/1.42/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 1

  # izmerenie5:
  #  - move: 0.193/1.62/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 1

  # izmerenie6:
  #  - move: 0.193/1.815/2.09
  #  - call: Izmerenie
  #  - call: Ohms
  #  - sleep: 1

  parkovka:
   - move: 0.45/1.07/2.09
   - call: PumpOff
   - score: 20
   - route_stop: epic
interrupts:
  flip!:
    - interrupt_condition: izmerenie0/call/1/purple
    - interrupt_condition: izmerenie1/call/1/purple
    - interrupt_condition: izmerenie2/call/1/purple
    - interrupt_condition: izmerenie3/call/1/purple
    - interrupt_condition: izmerenie4/call/1/purple
    - interrupt_condition: izmerenie5/call/1/purple
    - interrupt_condition: izmerenie6/call/1/purple
    - call: NadoPlitka
    - sleep: 0.4
    - call: NeNadoPlitka
  no_flip!:  
    - interrupt_condition: izmerenie0/call/1/yellow
    - interrupt_condition: izmerenie1/call/1/yellow
    - interrupt_condition: izmerenie2/call/1/yellow
    - interrupt_condition: izmerenie3/call/1/yellow
    - interrupt_condition: izmerenie4/call/1/yellow
    - interrupt_condition: izmerenie5/call/1/yellow
    - interrupt_condition: izmerenie6/call/1/yellow
    - interrupt_condition: izmerenie0/call/1/red
    - interrupt_condition: izmerenie1/call/1/red
    - interrupt_condition: izmerenie2/call/1/red
    - interrupt_condition: izmerenie3/call/1/red
    - interrupt_condition: izmerenie4/call/1/red
    - interrupt_condition: izmerenie5/call/1/red
    - interrupt_condition: izmerenie6/call/1/red
    - call: NeNadoPlitka
  park_inter:
    - interrupt_condition: timers/main/96
    - change_cost: 70
    - move: 0.45/1.07/2.09
    - score: 20  
  end_inter:
    - interrupt_condition: timers/main/99
    - change_cost: 0
    - call: PumpOff
    - route_stop: epic
