############################################ МАРШРУТ 1
tasks:

  za_statuetkoi:
    - move : 0.51/0.56/0
    - call : MicroArmHalf
    - call: PumOn
    - sleep: 0.2
    - move: 0.43/0.45/0
    - call: MicroArmUp

   zamena:
    - move: 0.43/0.45/0    ##поворачиваемся к реплике
    - move : 0.4/0.36/0
    - call : KubOtput
    - sleep: 0.1
    - call: KubInput

   sgruz:
    - move: 1.83/0.23/0   
    - move: 1.7/0.23/0
    - call: MicroArmDown

  izmerenie1:
   - move: 0.16/0.77/0
    

    

variables: #MUST BE INTS
  default: 0
  get_flipped_var: 1 
# interrupts:              # едем домой (врубить после теста всего маршрута)
#   return_to_base:
#     - interrupt_condition: "timers/main/50"
#     - move: 1/1/0
