############################################ МАРШРУТ 1
tasks:

  za_statuetkoi:
    - change_cost: 7
    - call: NeNadoPlitka
    - move : 1/0.44/1.8
    - move : 0.49/0.42/1.8
    - sleep: 0.5
    - move : 0.49/0.42/1.8
    - call : MicroArmHalf
    - call: PumpOn
    - sleep: 0.2
    - move: 0.37/0.34/1.8
    - call: MicroArmUp

  zamena:
    - move: 0.43/0.44/-2.15    ##поворачиваемся к реплике
    - move : 0.4/0.35/-2.15
    - sleep: 0.2
    - call : KubOutput
    - sleep: 0.1
    - call: KubInput

  sgruz:
    - move: 1.6/0.2/-2.10  
    - change_cost: 90
    - move: 1.77/0.2/-2.10   
    - call : MicroArmHalf
    - sleep: 0.2
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - call: ValveOff
    - sleep: 0.2
    - move: 1.7/0.23/-2.10
    - change_cost: 7
    - move: 1.6/0.23/-2.10
    - call: MicroArmDown
    

  izmerenie0:
    - move: 0.4/0.67/2.09
    - call: PumpOff
    - move: 0.17/0.67/2.09
    - call: Izmerenie
    - call: Ohms
    - sleep: 0.2

  izmerenie1:
    - move : 0.17/0.87/2.09
    - call: Izmerenie
    - call: Ohms
    - sleep: 0.2
    - call: NadoPlitka
    - sleep: 0.1
    - call: NeNadoPlitka
    

  izmerenie2:
   - move: 0.17/1.05/2.09
   - call: Izmerenie
   - call: Ohms
   - sleep: 0.2

  izmerenie3:
   - move: 0.17/1.24/2.09
   - call: Izmerenie
   - call: Ohms
   - sleep: 0.2

  izmerenie4:
   - move: 0.17/1.44/2.09
   - call: Izmerenie
   - call: Ohms
   - sleep: 0.2

  izmerenie5:
   - move: 0.17/1.62/2.09
   - call: Izmerenie
   - call: Ohms
   - sleep: 0.2

  izmerenie6:
   - move: 0.17/1.82/2.09
   - call: Izmerenie
   - call: Ohms
   - sleep: 0.2

  Parkovka:
   - move: 0.45/1.12/2.09
   - call: PumpOff
   - route_stop: epic
interrupts:
  flip!:
    - interrupt_condition: izmerenie0/call/1/yellow
    - interrupt_condition: izmerenie1/call/1/yellow
    - interrupt_condition: izmerenie2/call/1/yellow
    - interrupt_condition: izmerenie3/call/1/yellow
    - interrupt_condition: izmerenie4/call/1/yellow
    - interrupt_condition: izmerenie5/call/1/yellow
    - interrupt_condition: izmerenie6/call/1/yellow
    - call: NadoPlitka
    - sleep: 1
    - call: NeNadoPlitka
  no_flip!:  
    - interrupt_condition: izmerenie0/call/1/purple
    - interrupt_condition: izmerenie1/call/1/purple
    - interrupt_condition: izmerenie2/call/1/purple
    - interrupt_condition: izmerenie3/call/1/purple
    - interrupt_condition: izmerenie4/call/1/purple
    - interrupt_condition: izmerenie5/call/1/purple
    - interrupt_condition: izmerenie6/call/1/purple
    - interrupt_condition: izmerenie0/call/1/red
    - interrupt_condition: izmerenie1/call/1/red
    - interrupt_condition: izmerenie2/call/1/red
    - interrupt_condition: izmerenie3/call/1/red
    - interrupt_condition: izmerenie4/call/1/red
    - interrupt_condition: izmerenie5/call/1/red
    - interrupt_condition: izmerenie6/call/1/red
    - call: NeNadoPlitka
  end_inter:
    - interrupt_condition: timers/main/99
    - call: PumpOff