"ArmUp":
- "servos_service":
  - num: 0
  - state: true
- "servos_service":
  - num: 1
  - state: false
- "servos_service":
  - num: 2
  - state: true
  
"ArmDown":
- "servos_service":
  - num: 0
  - state: false
- "servos_service":
  - num: 1
  - state: true
- "servos_service":
  - num: 2
  - state: false