#Available services: servos_service
"Static":
"ArmUp":
- "servos_service":
  - "num": 0
  - "state": 1
- "servos_service":
  - "num": 1
  - "state": 0
- "servos_service":
  - "num": 2
  - "state": 1
  
"ArmDown":
- "servos_service":
  - "num": 0
  - "state": 0
- "servos_service":
  - "num": 1
  - "state": 1
- "servos_service":
  - "num": 2
  - "state": 0

"Dynamic":
"Example":
  - custom_arg1
  - custom_arg2
"Move_servo":
  - "num"
  - "state"