interrupts:
  1:
    - inter_condition: "calls/epic_service/bad"
    - call: "test"
    - move: "1/1"
    
  2: 
    - call: "test2"
tasks:
  1:
    - call: "ArmUp"
    - move: "1/1"
    - log: "L:Moving to 1m/1m" 
    #Prefixes (L:/W:/E:) = (Log, Warn, Error)
  2:
    - call: "test3"
    - together: 
      - move: "1/2"
      - call: "cbt"
    - condition: 
      - if: "calls/ArmUp/1"
      - do: 
          together:
            - call : "epic"
            - skip: "3"
      - else: 
        - skip: "2"
    - log: "Skipping task 2, bc test3 good"
    - move: "2/2"
  3: 
    - call: "test4"
    - interrupt: "2"

        