interrupts:
  1:
    - inter_condition: "calls/epic_service/bad"
    - call: "test"
    - move: "1/1"
    
  2: 
    - call: "test2"
# NEVER CALL TWO MOVES SIMULTANEOUSLY!!!
tasks:
  Start:
    - call: ArmUp
    - dynamic_call: #always use dynamic_call!!
      - Move_servo
      - num: 0 #kwargs
      - state: 1
    - move: "1/1/2" #x/y/th
    - log: "W:Moving to 1m/1m" 
    #Prefixes (L:/W:/E:) = (Log, Warn, Error)
  Epic_task:
    - together: 
      - move: 1/2/3
      - call: ArmDown
    - sleep: 4 #in secs
    - condition: 
      - if: "calls/ArmUp/1"
      - do: 
          together:
            - call : "ArmUp"
            - skip: "3"
      - else: 
          skip: "2"
    - log: "E:Skipping task 2, bc test3 good"
    - move: "2/2/0"
  Da_vinki??: 
    - dynamic_call: #always use dynamic_call!!
      - Move_servo
      - num: 0 #kwargs
      - state: 1
    #- interrupt: "2"
    - score: 2 #plus
    #- interrupt_switch_on: 2
    #- interrupt_switch_off: 2

        