tasks:
  
  get_flipped: 
    - move: 1.68/1.39/-1.047
    - call: ArmHalfDown
    - call: PumpOn
    - move: 1.75/1.39/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.39/-1.047
    - score: 1
  deliver_blue_flipped:
    - log: "W: Delivering blue"
    - move: 1.68/0.61/-1.047
    - move: 1.81/0.61/-1.047
    #- call: ArmHalfUp
    - call: ValveOn
    - sleep: 0.3
    - call: PumpOff
    - call: ValveOff
    - score: 3
    - move: 1.68/0.61/-1.047
    - call: ArmDown
    get_flipped2:
    - move: 1.68/1.45/-1.047
    - call: ArmHalfDown
    - call: PumpOn
    - move: 1.75/1.39/-1.047
    - sleep: 0.2
    - call: ArmUp
    - sleep: 0.1
    - move: 1.68/1.39/-1.047
    - score: 1

  home:
    - log: "W: Going home!"
    - move: 1.4/0.25/1.57
    - score: 20 #20 for return 1 for hexagon

variables: #MUST BE INTS
  default: 0
  get_flipped_var: 1 
#interrupts: 
  # return_to_base:
  #   - interrupt_condition: "timers/main/40"
  #   - move: 1/0.4/1.5 
