interrupts:
  1:
    - call: "test"
    - move: "1/1"
  2: 
    - call: "test2"
tasks:
  1:
    - call: "test"
    - move: "1/1"
    - log: "Moving to 1m/1m"
  2:
    - call: "test3"
    - wait:
      - condition: "test3/bad"
      - actions: 
        - call : "epic"
        - "skip/3"
      - else: "skip/2"
      - log: "Skipping task 2, bc test3 good"
    - move: "2/2"
  3: 
    - call: "test4"
    - schedule:
      - condition: "service/epic_service/bad"
      - interrupt: "2"
    
        