tasks:
  start: 
    - move: 1/1.5/0
    - score: 10
    - sleep: 1
  top:
    - move: 1.5/1/3.14
    - score: -5
    - dynamic_call:
      - MoveServo
      - num: 0
      - state: 1
    - sleep: 1
  left:
    - move: 0.5/1/0
    - score: 55
    - sleep: 1
  return:
    - move: 1/1.5/0
    - score: 10

interrupts: 
  return_to_base:
    - interrupt_condition: "timer/route/90"
    - move: 1/0.2/1.5