tasks:
  start: 
    - move: 1/1.5/0
    - score: 10  
    - group:  #Things in group are done in parallel
      - log: "W:Testing group" 
      - sleep: 1
      - log: "E:Testing group"
    - call: Adjust
  top:
    - move: 1.5/1/1
    - log: "E: EPIC TEST INCOMING"
    - condition:
      - if: "start/sleep/0/fail"
      - do: 
        - log: "W: EPIC TEST PASSED!"
      - else: 
        - log: "E: EPIC TEST FAILED!!"
    - score: -5
    - call: ArmUp
    - dynamic_call:
      - MoveServo
      - num: 0
      - state: 1
    - sleep: 1
  left:
    - move: 0.5/1/0
    - score: 55
    - sleep: 1
  return:
    - move: 1/1.5/0
    - score: 9
    - goto: start

interrupts: 
  return_to_base:
    - interrupt_condition: "timer/main/35"
    - move: 1/0.4/1.5 