tasks: #move: x/y/th
  top_right: 
    - call: ArmUp
    - call: ArmHalfUp
    - call: ArmHalfDown
    - call: ArmDown
    - call: Adjust
    - move: 1.02/0.44/0 
    - call: Adjust
  top_left:
    - move: 1.62/0.44/1
    - call: Adjust
  start:
    - move: 0.8/0.4/3.6
    - call: Adjust
    - score: 1000
variables:
  default: 0


