tasks: #move: x/y/th
  top_right: 
    - call: PumpOn
    - call: ValveOn
    - call: ArmUp
    - sleep: 0.5
    - call: ArmHalfUp
    - sleep: 0.5
    - call: ArmHalfDown
    - sleep: 0.5
    - call: ArmDown
    - sleep: 0.5
    - call: Adjust
    - move: 1.02/0.44/0 
    - call: Adjust
    - call: PumpOff
    - call: ValveOff
  top_left:
    - move: 1.62/0.44/0
    - call: Adjust
  start:
    - move: 1.4/0.25/5.5
    - call: Adjust
    - score: 1000
variables:
  default: 0


