tasks:
  top_right: 
    - call: ArmUp
    - call: Adjust
    - move: 1/0.55/0 #x/y/th
    - call: Adjust
  top_left:
    - move: 0.7/0.55/1
    - call: Adjust
  start:
    - call: Adjust
    - move: 0.8/0.4/0
    - score: 1000
    - call: Adjust
variables:
  default: 0


