motors_info_callback:
  default_side: 2 #purple - default
  side_topic: ebobot/begin
  #
  2/start_x: 1.2
  2/start_y: 0.14
  2/start_theta: 1.57
  ########
  1/start_x: 1.2
  1/start_y: 2.9
  1/start_theta: -1.57
  ########
  footprint_radius: 0.09
  update_rate: 20
  #####
  theta_coeff: 1.37
  y_coeff: 1
  x_coeff: 1