laser_scan_callback:
  update_rate: 10
  beacons:
    adjust_on_command: 1
    cycles_per_update: 4
    min_rad: 0.005
    max_rad: 0.25
    max_dist_from_expected: 0.3
    adjust_time: 2
    pub_all: 1
    num_beacons: 3 #needed for proper auto-init
    beacon0:
  - 0.02 #meters, y
  - 1    #meters, x
    beacon1:
  - 2.99
  - 0.01
    beacon2:
  - 2.99
  - 1.99
