new_task_manager:
  calls_debug: 0
  start_service: /ebobot/begin
  status:
    update_rate: 10
    reduce_update_rate_for_move: 4 #how much slower move updates than statuses
  allowed_script_commands:
    - parse
    - exec_route
    - countdown
  scripts:
    - parse/0/countdown/3/exec_route