# Available services: 
# servos_service, prediction_service
# ohm_reader_service, adjust_pos_service
"Static":
  - "Adjust":
    - "adjust_pos_service":
      - "empty": 0 #even if the call is empty you should state at least one argument in static call
  - "ArmUp":
    - "servos_service":
      - "num": 0
      - "state": 100
    - "servos_service":
      - "num": 1
      - "state": 30
    - "servos_service":
      - "num": 2
      - "state": 100

  - "ArmDown":
    - "servos_service":
      - "num": 0
      - "state": 0
    - "servos_service":
      - "num": 1
      - "state": 1
    - "servos_service":
      - "num": 2
      - "state": 0

  - "OhmsWithServos":
    - "servos_service":
      - "num": 3
      - "state": 0
    - "servos_service":
      - "num": 4
      - "state": 1
    - "ohm_reader_service":
      - "pin": 1


      
"Dynamic": #plain call of service, but one at a time!
  - "Example": #with kwargs!
    - service_name # call with args passed as: {service_arg_1: arg1, service_arg_2: arg2}
  - "MoveServo":
    - "servos_service"
  - "ShowPrediction":
    - "prediction_service"
  - "OhmReader":
    - "ohm_reader_service"