#Available services: servos_service, lcd_service
"Static":
  - "ArmUp":
    - "servos_service":
      - "num": 0
      - "state": 1
    - "servos_service":
      - "num": 1
      - "state": 0
    - "servos_service":
      - "num": 2
      - "state": 1

  - "ArmDown":
    - "servos_service":
      - "num": 0
      - "state": 0
    - "servos_service":
      - "num": 1
      - "state": 1
    - "servos_service":
      - "num": 2
      - "state": 0

  - "OhmsWithServos":
    - "servos_service":
      - "num": 3
      - "state": 0
    - "servos_service":
      - "num": 4
      - "state": 1
    - "ohm_reader_service":
      - "pin": 1
"Dynamic": #plain call of service, but one at a time!
  - "Example": #with kwargs!
    - service1
    - service2
  - "MoveServo":
    - "servos_service"
  - "ShowPrediction":
    - "prediction_service"
  - "OhmReader":
    - "ohm_reader_service"